version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  distributedCache:
    image: redis

  orderdb:
    image: mcr.microsoft.com/mssql/server

  catalog.api:
    build:
      context: ..
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    build:
      context: ..
      dockerfile: src/Services/Basket/Basket.API/Dockerfile

  discount.grpc:
    build:
      context: ./Services/Discount/Discount.Grpc
      dockerfile: Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
